In [1]:
import numpy as np 
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([[1,2,3],[4,5,6]])

print(arr1)
print(arr2)

print("type:",type(arr1))
print("shape:", arr2.shape)
print("size:", arr2.size)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
type: <class 'numpy.ndarray'>
shape: (2, 3)
size: 6

In [2]:
import numpy as np
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
import numpy as np
import pandas as pda

arr1 = np.array([1,2,3,4,5,6,7])
arr1.mean()
mean = np.median(arr1)
std = np.std(arr1)

print(arr1)
print(mean)
print(std)

arr1_squar = arr1**2
print(arr1_squar)

[1 2 3 4 5 6 7]
4.0
2.0
[ 1  4  9 16 25 36 49]

In [4]:
import numpy as np 

l1 = [ 1,2,3,4]
l2 = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]

list(zip(l1,l2))

[(1, [1, 2, 3]), (2, [4, 5, 6]), (3, [7, 8, 9]), (4, [10, 11, 12])]

In [5]:
import numpy as np
import sys 

list = [1,2,3,4,5]
arr = np.array([1,2,3,4,5])

print("size of list:", sys.getsizeof(list))
print("size of array:", arr.nbytes)

size of list: 104
size of array: 40

In [6]:
import numpy as np

# arr = np.linspace(1,100,5)
# print(arr)

#  np.arange(1,100,10)
np.ones((2,3))
# np.full((2,3),5)

array([[1., 1., 1.],
       [1., 1., 1.]])

CREATING ARRAY & USING ARRAY PROPERTIES

In [7]:
import numpy as np
myarr = np.array([[1,2,3,4],[5,6,7,8],[11,12,13,14]])
print(myarr)

print("shape of myarr:",myarr.shape)
print("size of myarr:",myarr.size )
print("Dimensions:", myarr.ndim)
print("Dta Type:",myarr.dtype)

reshaped = myarr.reshape((2,6))
print(reshaped)

flattened = myarr.flatten()
print(flattened)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [11 12 13 14]]
shape of myarr: (3, 4)
size of myarr: 12
Dimensions: 2
Dta Type: int64
[[ 1  2  3  4  5  6]
 [ 7  8 11 12 13 14]]
[ 1  2  3  4  5  6  7  8 11 12 13 14]

FANCY INDEXING AND BOLLEAN MASKING

In [8]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,11,12,13,14])
print(arr)

print(arr[0],arr[5],arr[8])
print(arr[:5] , arr[6:])

b = arr[3:7]
print(b)             # cutting arr b out of main array

b[0] = 99      #changing the first element of b 

print(b)
print(arr)         # change in main array 


#FANCY INDEXING 
idx = [ 0,2,4,6]             #INDICATING INDEXS TO BE SELECTED
print(arr[idx])             #OUTPUT--> [ 1 3 5 7]

#BOOLEAN MASKING
mask = arr>5
print(mask)
print(arr[mask])

[ 1  2  3  4  5  6  7  8 11 12 13 14]
1 6 11
[1 2 3 4 5] [ 7  8 11 12 13 14]
[4 5 6 7]
[99  5  6  7]
[ 1  2  3 99  5  6  7  8 11 12 13 14]
[1 3 5 7]
[False False False  True False  True  True  True  True  True  True  True]
[99  6  7  8 11 12 13 14]

DATA TYPES

In [9]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr.dtype)

arr.astype("float64")

int64

array([1., 2., 3., 4., 5.])

In [10]:
import numpy as np

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([4,5,6])

result = arr1+arr2
print(result)

[[ 5  7  9]
 [ 8 10 12]]

In [11]:
import numpy as np

arr1 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

mean = arr1.mean()
std = arr1.std()

print(mean)
print(std)

normalized_data = (arr1-mean)/std
print(normalized_data)

5.0
2.581988897471611
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]

PANDAS

In [12]:
import pandas as pd

s = pd.Series([10,20,30,40], index = ['a','b','c','d'])
print(s)
print(type(s))

a    10
b    20
c    30
d    40
dtype: int64
<class 'pandas.Series'>

In [13]:
import numpy as np
import pandas as pd

df = pd.read_csv("tips.csv")
print(df.head(10))
print(df.tail)

df.query("total_bill > 12 and size > 2")

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2
<bound method NDFrame.tail of      total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]>

     total_bill   tip     sex smoker  day    time  size
2         21.01  3.50    Male     No  Sun  Dinner     3
4         24.59  3.61  Female     No  Sun  Dinner     4
5         25.29  4.71    Male     No  Sun  Dinner     4
7         26.88  3.12    Male     No  Sun  Dinner     4
11        35.26  5.00  Female     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
227       20.45  3.00    Male     No  Sat  Dinner     4
230       24.01  2.00    Male    Yes  Sat  Dinner     4
231       15.69  3.00    Male    Yes  Sat  Dinner     3
238       35.83  4.67  Female     No  Sat  Dinner     3
239       29.03  5.92    Male     No  Sat  Dinner     3

[82 rows x 7 columns]

In [14]:
import numpy as np
import pandas as pd 

df = pd.read_csv("banklist.csv")
# print(df.head())
# print(df.tail())
# print(df.info())
# print(df.describe())
# print(df[['City','Bank Name']])
# print(df.iloc[1])         # iloc me hum use krte hai index ko 
# print(df.loc[1])          #loc me hum use krte h level ko

print(df.loc[ 98,'City'])
print(df.iloc[ 100 ,1])
print(df.loc[0:10 ,['City','Bank Name']])

Richmond
Sarasota
            City                                 Bank Name
0        Kenosha  Banks of Wisconsin d/b/a Bank of Kenosha
1     Scottsdale                      Central Arizona Bank
2       Valdosta                              Sunrise Bank
3      Asheville                     Pisgah Community Bank
4   Douglasville                       Douglas County Bank
5         Lenoir                              Parkway Bank
6       Marianna                    Chipola Community Bank
7    Orange Park            Heritage Bank of North Florida
8      Lexington                        First Federal Bank
9    Gold Canyon                          Gold Canyon Bank
10      LaGrange                             Frontier Bank

In [15]:
print(df.loc[0:10 , ['City','Bank Name']])

            City                                 Bank Name
0        Kenosha  Banks of Wisconsin d/b/a Bank of Kenosha
1     Scottsdale                      Central Arizona Bank
2       Valdosta                              Sunrise Bank
3      Asheville                     Pisgah Community Bank
4   Douglasville                       Douglas County Bank
5         Lenoir                              Parkway Bank
6       Marianna                    Chipola Community Bank
7    Orange Park            Heritage Bank of North Florida
8      Lexington                        First Federal Bank
9    Gold Canyon                          Gold Canyon Bank
10      LaGrange                             Frontier Bank

In [16]:
print(df.at[1,'City'])
print(df.iat[1,1])

Scottsdale
Scottsdale

In [17]:
df[df['CERT']> 58200]

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
3,Pisgah Community Bank,Asheville,NC,58701,"Capital Bank, N.A.",10-May-13,14-May-13
66,Premier Community Bank of the Emerald Coast,Crestview,FL,58343,Summit Bank,16-Dec-11,12-Sep-12
87,CreekSide Bank,Woodstock,GA,58226,Georgia Commerce Bank,2-Sep-11,6-Sep-12
88,Patriot Bank of Georgia,Cumming,GA,58273,Georgia Commerce Bank,2-Sep-11,2-Nov-12
97,"BankMeridian, N.A.",Columbia,SC,58222,SCBT National Association,29-Jul-11,2-Nov-12
98,Virginia Business Bank,Richmond,VA,58283,Xenith Bank,29-Jul-11,9-Oct-12
105,One Georgia Bank,Atlanta,GA,58238,Ameris Bank,15-Jul-11,2-Nov-12
112,Atlantic Bank and Trust,Charleston,SC,58420,"First Citizens Bank and Trust Company, Inc.",3-Jun-11,31-Oct-12
120,First Choice Community Bank,Dallas,GA,58539,Bank of the Ozarks,29-Apr-11,22-Jan-13
160,"Appalachian Community Bank, FSB",McCaysville,GA,58495,Peoples Bank of East Tennessee,17-Dec-10,31-Oct-12
183,WestBridge Bank and Trust Company,Chesterfield,MO,58205,Midland States Bank,15-Oct-10,20-Aug-12
188,Haven Trust Bank Florida,Ponte Vedra Beach,FL,58308,First Southern Bank,24-Sep-10,5-Nov-12
252,Champion Bank,Creve Coeur,MO,58362,BankLiberty,30-Apr-10,23-Aug-12
257,Wheatland Bank,Naperville,IL,58429,Wheaton Bank & Trust,23-Apr-10,23-Aug-12
293,Carson River Community Bank,Carson City,NV,58352,Heritage Bank of Nevada,26-Feb-10,15-Jan-13
320,RockBridge Commercial Bank,Atlanta,GA,58315,No Acquirer,18-Dec-09,5-Nov-12
322,"Valley Capital Bank, N.A.",Mesa,AZ,58399,Enterprise Bank & Trust,11-Dec-09,23-Aug-12
352,Hillcrest Bank Florida,Naples,FL,58336,Stonegate Bank,23-Oct-09,22-Aug-12
463,Alpha Bank & Trust,Alpharetta,GA,58241,"Stearns Bank, N.A.",24-Oct-08,16-Aug-12

In [18]:
#filtering BANK NAME only

df[df['CERT']> 58400]['Bank Name']
# df1 = df[['Bank Name','City']]

3                Pisgah Community Bank
112            Atlantic Bank and Trust
120        First Choice Community Bank
160    Appalachian Community Bank, FSB
257                     Wheatland Bank
Name: Bank Name, dtype: str

In [19]:
import pandas as pd 
import numpy as np

df = pd.read_csv("banklist.csv")
print(df.head(10))

                                  Bank Name          City  ST   CERT  \
0  Banks of Wisconsin d/b/a Bank of Kenosha       Kenosha  WI  35386
1                      Central Arizona Bank    Scottsdale  AZ  34527
2                              Sunrise Bank      Valdosta  GA  58185
3                     Pisgah Community Bank     Asheville  NC  58701
4                       Douglas County Bank  Douglasville  GA  21649
5                              Parkway Bank        Lenoir  NC  57158
6                    Chipola Community Bank      Marianna  FL  58034
7            Heritage Bank of North Florida   Orange Park  FL  26680
8                        First Federal Bank     Lexington  KY  29594
9                          Gold Canyon Bank   Gold Canyon  AZ  58066

                         Acquiring Institution Closing Date Updated Date
0                        North Shore Bank, FSB    31-May-13    31-May-13
1                           Western State Bank    14-May-13    20-May-13
2                                 Synovus Bank    10-May-13    21-May-13
3                           Capital Bank, N.A.    10-May-13    14-May-13
4                          Hamilton State Bank    26-Apr-13    16-May-13
5             CertusBank, National Association    26-Apr-13    17-May-13
6                First Federal Bank of Florida    19-Apr-13    16-May-13
7                           FirstAtlantic Bank    19-Apr-13    16-May-13
8                          Your Community Bank    19-Apr-13    23-Apr-13
9  First Scottsdale Bank, National Association     5-Apr-13     9-Apr-13